#ifndef INC_DISPLAY_DRIVER_H_
#define INC_DISPLAY_DRIVER_H_

/* Active display driver. Keep one include enabled and the other commented. */
#include "ili9341.h"
//#include "st7789.h"

/* Active touch driver. Keep one include enabled and the other commented. */
#include "ili9341_touch.h"
//#include "st7789_touch.h"

#if defined(__ILI9341_H__)
#define DISPLAY_SPI_PORT ILI9341_SPI_PORT

#define DISPLAY_MADCTL_MY  ILI9341_MADCTL_MY
#define DISPLAY_MADCTL_MX  ILI9341_MADCTL_MX
#define DISPLAY_MADCTL_MV  ILI9341_MADCTL_MV
#define DISPLAY_MADCTL_ML  ILI9341_MADCTL_ML
#define DISPLAY_MADCTL_RGB ILI9341_MADCTL_RGB
#define DISPLAY_MADCTL_BGR ILI9341_MADCTL_BGR
#define DISPLAY_MADCTL_MH  ILI9341_MADCTL_MH

#define DISPLAY_ORIENTATION_PORTRAIT        ILI9341_ORIENTATION_PORTRAIT
#define DISPLAY_ORIENTATION_PORTRAIT_UPSIDE ILI9341_ORIENTATION_PORTRAIT_UPSIDE
#define DISPLAY_ORIENTATION_LANDSCAPE       ILI9341_ORIENTATION_LANDSCAPE
#define DISPLAY_ORIENTATION_LANDSCAPE_LEFT  ILI9341_ORIENTATION_LANDSCAPE_LEFT

#define display_orientation  ili9341_orientation
#define DISPLAY_SCREEN_WIDTH ILI9341_SCREEN_WIDTH
#define DISPLAY_SCREEN_HEIGHT ILI9341_SCREEN_HEIGHT
#define DISPLAY_TOUCH_SCALE_X ILI9341_TOUCH_SCALE_X
#define DISPLAY_TOUCH_SCALE_Y ILI9341_TOUCH_SCALE_Y

#define DISPLAY_TOUCH_MIN_RAW_X ILI9341_TOUCH_MIN_RAW_X
#define DISPLAY_TOUCH_MAX_RAW_X ILI9341_TOUCH_MAX_RAW_X
#define DISPLAY_TOUCH_MIN_RAW_Y ILI9341_TOUCH_MIN_RAW_Y
#define DISPLAY_TOUCH_MAX_RAW_Y ILI9341_TOUCH_MAX_RAW_Y

#define DISPLAY_DC_Pin ILI9341_DC_Pin
#define DISPLAY_DC_GPIO_Port ILI9341_DC_GPIO_Port
#define DISPLAY_RES_Pin ILI9341_RES_Pin
#define DISPLAY_RES_GPIO_Port ILI9341_RES_GPIO_Port
#define DISPLAY_CS_Pin ILI9341_CS_Pin
#define DISPLAY_CS_GPIO_Port ILI9341_CS_GPIO_Port

#define DISPLAY_BLACK   ILI9341_BLACK
#define DISPLAY_BLUE    ILI9341_BLUE
#define DISPLAY_RED     ILI9341_RED
#define DISPLAY_GREEN   ILI9341_GREEN
#define DISPLAY_CYAN    ILI9341_CYAN
#define DISPLAY_MAGENTA ILI9341_MAGENTA
#define DISPLAY_YELLOW  ILI9341_YELLOW
#define DISPLAY_WHITE   ILI9341_WHITE
#define DISPLAY_ORANGE      ILI9341_ORANGE
#define DISPLAY_PURPLE      ILI9341_PURPLE
#define DISPLAY_PINK        ILI9341_PINK
#define DISPLAY_LIME        ILI9341_LIME
#define DISPLAY_TEAL        ILI9341_TEAL
#define DISPLAY_GRAY        ILI9341_GRAY
#define DISPLAY_DARK_BLUE   ILI9341_DARK_BLUE
#define DISPLAY_DARK_RED    ILI9341_DARK_RED
#define DISPLAY_DARK_GREEN  ILI9341_DARK_GREEN
#define DISPLAY_BROWN       ILI9341_BROWN

#define DISPLAY_COLOR565 ILI9341_COLOR565

#define DISPLAY_Unselect ILI9341_Unselect
#define DISPLAY_Init ILI9341_Init
#define DISPLAY_SetOrientation ILI9341_SetOrientation
#define DISPLAY_InvertColors ILI9341_InvertColors
#define DISPLAY_DrawPixel ILI9341_DrawPixel
#define DISPLAY_WriteString ILI9341_WriteString
#define DISPLAY_FillRectangle ILI9341_FillRectangle
#define DISPLAY_FillScreen ILI9341_FillScreen
#define DISPLAY_DrawImage ILI9341_DrawImage
#define DISPLAY_DrawLine ILI9341_DrawLine
#define DISPLAY_DrawRect ILI9341_DrawRect
#define DISPLAY_DrawCircle ILI9341_DrawCircle
#define DISPLAY_FillCircle ILI9341_FillCircle
#define DISPLAY_FillScreen_DMA ILI9341_FillScreen_DMA
#define DISPLAY_FillRectangle_DMA ILI9341_FillRectangle_DMA
#define DISPLAY_WriteString_DMA ILI9341_WriteString_DMA
#define DISPLAY_DrawImage_DMA ILI9341_DrawImage_DMA
#define DISPLAY_FillCircle_DMA ILI9341_FillCircle_DMA
#define DISPLAY_DrawImage_DMA_1D ILI9341_DrawImage_DMA_1D
#elif defined(__ST7789_H__)
#define DISPLAY_SPI_PORT ST7789_SPI_PORT

#define DISPLAY_MADCTL_MY  ST7789_MADCTL_MY
#define DISPLAY_MADCTL_MX  ST7789_MADCTL_MX
#define DISPLAY_MADCTL_MV  ST7789_MADCTL_MV
#define DISPLAY_MADCTL_ML  ST7789_MADCTL_ML
#define DISPLAY_MADCTL_RGB ST7789_MADCTL_RGB
#define DISPLAY_MADCTL_BGR ST7789_MADCTL_BGR
#define DISPLAY_MADCTL_MH  ST7789_MADCTL_MH

#define DISPLAY_ORIENTATION_PORTRAIT        ST7789_ORIENTATION_PORTRAIT
#define DISPLAY_ORIENTATION_PORTRAIT_UPSIDE ST7789_ORIENTATION_PORTRAIT_UPSIDE
#define DISPLAY_ORIENTATION_LANDSCAPE       ST7789_ORIENTATION_LANDSCAPE
#define DISPLAY_ORIENTATION_LANDSCAPE_LEFT  ST7789_ORIENTATION_LANDSCAPE_LEFT

#define display_orientation  st7789_orientation
#define DISPLAY_SCREEN_WIDTH ST7789_SCREEN_WIDTH
#define DISPLAY_SCREEN_HEIGHT ST7789_SCREEN_HEIGHT
#define DISPLAY_TOUCH_SCALE_X ST7789_TOUCH_SCALE_X
#define DISPLAY_TOUCH_SCALE_Y ST7789_TOUCH_SCALE_Y

#define DISPLAY_TOUCH_MIN_RAW_X ST7789_TOUCH_MIN_RAW_X
#define DISPLAY_TOUCH_MAX_RAW_X ST7789_TOUCH_MAX_RAW_X
#define DISPLAY_TOUCH_MIN_RAW_Y ST7789_TOUCH_MIN_RAW_Y
#define DISPLAY_TOUCH_MAX_RAW_Y ST7789_TOUCH_MAX_RAW_Y

#define DISPLAY_DC_Pin ST7789_DC_Pin
#define DISPLAY_DC_GPIO_Port ST7789_DC_GPIO_Port
#define DISPLAY_RES_Pin ST7789_RES_Pin
#define DISPLAY_RES_GPIO_Port ST7789_RES_GPIO_Port
#define DISPLAY_CS_Pin ST7789_CS_Pin
#define DISPLAY_CS_GPIO_Port ST7789_CS_GPIO_Port

#define DISPLAY_BLACK   ST7789_BLACK
#define DISPLAY_BLUE    ST7789_BLUE
#define DISPLAY_RED     ST7789_RED
#define DISPLAY_GREEN   ST7789_GREEN
#define DISPLAY_CYAN    ST7789_CYAN
#define DISPLAY_MAGENTA ST7789_MAGENTA
#define DISPLAY_YELLOW  ST7789_YELLOW
#define DISPLAY_WHITE   ST7789_WHITE
#define DISPLAY_ORANGE      ST7789_ORANGE
#define DISPLAY_PURPLE      ST7789_PURPLE
#define DISPLAY_PINK        ST7789_PINK
#define DISPLAY_LIME        ST7789_LIME
#define DISPLAY_TEAL        ST7789_TEAL
#define DISPLAY_GRAY        ST7789_GRAY
#define DISPLAY_DARK_BLUE   ST7789_DARK_BLUE
#define DISPLAY_DARK_RED    ST7789_DARK_RED
#define DISPLAY_DARK_GREEN  ST7789_DARK_GREEN
#define DISPLAY_BROWN       ST7789_BROWN

#define DISPLAY_COLOR565 ST7789_COLOR565

#define DISPLAY_Unselect ST7789_Unselect
#define DISPLAY_Init ST7789_Init
#define DISPLAY_SetOrientation ST7789_SetOrientation
#define DISPLAY_InvertColors ST7789_InvertColors
#define DISPLAY_DrawPixel ST7789_DrawPixel
#define DISPLAY_WriteString ST7789_WriteString
#define DISPLAY_FillRectangle ST7789_FillRectangle
#define DISPLAY_FillScreen ST7789_FillScreen
#define DISPLAY_DrawImage ST7789_DrawImage
#define DISPLAY_DrawLine ST7789_DrawLine
#define DISPLAY_DrawRect ST7789_DrawRect
#define DISPLAY_DrawCircle ST7789_DrawCircle
#define DISPLAY_FillCircle ST7789_FillCircle
#define DISPLAY_FillScreen_DMA ST7789_FillScreen_DMA
#define DISPLAY_FillRectangle_DMA ST7789_FillRectangle_DMA
#define DISPLAY_WriteString_DMA ST7789_WriteString_DMA
#define DISPLAY_DrawImage_DMA ST7789_DrawImage_DMA
#define DISPLAY_FillCircle_DMA ST7789_FillCircle_DMA
#define DISPLAY_DrawImage_DMA_1D ST7789_DrawImage_DMA_1D
#else
#error "No active display driver selected in display_driver.h"
#endif

#if defined(__ILI9341_TOUCH_H__)
#define DISPLAY_TOUCH_SPI_PORT ILI9341_TOUCH_SPI_PORT
#define DISPLAY_TOUCH_CS_Pin ILI9341_TOUCH_CS_Pin
#define DISPLAY_TOUCH_CS_GPIO_Port ILI9341_TOUCH_CS_GPIO_Port
#define DISPLAY_TOUCH_IRQ_Pin ILI9341_TOUCH_IRQ_Pin
#define DISPLAY_TOUCH_IRQ_GPIO_Port ILI9341_TOUCH_IRQ_GPIO_Port

#define DISPLAY_TouchUnselect ILI9341_TouchUnselect
#define DISPLAY_TouchPressed ILI9341_TouchPressed
#define DISPLAY_TouchGetCoordinates ILI9341_TouchGetCoordinates
#elif defined(__ST7789_TOUCH_H__)
#define DISPLAY_TOUCH_SPI_PORT ST7789_TOUCH_SPI_PORT
#define DISPLAY_TOUCH_CS_Pin ST7789_TOUCH_CS_Pin
#define DISPLAY_TOUCH_CS_GPIO_Port ST7789_TOUCH_CS_GPIO_Port
#define DISPLAY_TOUCH_IRQ_Pin ST7789_TOUCH_IRQ_Pin
#define DISPLAY_TOUCH_IRQ_GPIO_Port ST7789_TOUCH_IRQ_GPIO_Port

#define DISPLAY_TouchUnselect ST7789_TouchUnselect
#define DISPLAY_TouchPressed ST7789_TouchPressed
#define DISPLAY_TouchGetCoordinates ST7789_TouchGetCoordinates
#else
#error "No active touch driver selected in display_driver.h"
#endif

#endif /* INC_DISPLAY_DRIVER_H_ */
