#ifndef INC_RENDER_SCRATCH_H_
#define INC_RENDER_SCRATCH_H_

#include <stdint.h>

#define RENDER_SCRATCH_PATCH_WIDTH   160U
#define RENDER_SCRATCH_PATCH_HEIGHT   48U
#define RENDER_SCRATCH_BUFFER_SIZE   \
    (RENDER_SCRATCH_PATCH_WIDTH * RENDER_SCRATCH_PATCH_HEIGHT * 2U)

extern uint8_t render_scratch_buffer[RENDER_SCRATCH_BUFFER_SIZE];

#endif /* INC_RENDER_SCRATCH_H_ */
